### ISSUE TITLE
ofxJson vs ofxJsonElement

### ISSUE THREAD

**Issue by armadillu** [mattfelsen/ofxJsonSettings#2]
Hey Matt I was going to use this but I see your PR to ofxJson is still on hold... I rely on that class name on other JSON stuff, so that means I can't use your addon as it is. Maybe you can do some ifdef macro magic so it can work with both names in the meantime?

**Comment by armadillu** [comment]
oh I see the typedef you have defined on the lp fork at project/mcny does just that

**Comment by mattfelsen** [comment]
Yea I think I wanted it to be `ofxJSON` and didn't want to wait for that PR to get merged upstream so just forked in in the LP account. Does that work for what you need? If so can I close this issue?

**Comment by armadillu** [comment]
that works now thx!  but I can't seem to get it to load anything - different issue. And looking at the code I have no idea how it load anything for you either?
