### ISSUE TITLE
Can I get and save JSON array?

### ISSUE THREAD

**Issue by taejaehan** [mattfelsen/ofxJsonSettings#5]
Hello. Thank you for this addon.
I have a question.

Can I get and save JSON array like below form.

{
 "A" : [1, 3, 66, 13, 20, 42]
}

Thank you.

**Comment by mattfelsen** [comment]
Hi @taejaehan. If you just want to save & load the contents of your settings from your app to a file, there's an example show here:
https://github.com/mattfelsen/ofxJsonSettings#load

If you want to serialize the settings data as a string without writing to a file, you can use the `getAsJsonString()` method seen here:
https://github.com/mattfelsen/ofxJsonSettings/blob/29afd4a70fc50abaadac433647a4d160fd485a72/src/ofxJsonSettings.cpp#L102

Does that help with what you're trying to do?

**Comment by taejaehan** [comment]
Thank you for the answer.

I just wanted to make a JSON file from my data.
And I was trying to figure out if there's a way to make the value of key as Array not string.

But, the string value will be fine too. 

Anyway thank you.
